// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-event-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_event_info_default = defineTool({
  name: "get_event_info",
  title: "Get REST Reset event info",
  description: "Returns the REST Reset event schedule, timezone, and session times.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "REST Reset",
          host: "Learning While Healing",
          dates: "July 28\u201330, 2026",
          days: "Tuesday to Thursday",
          sessionTime: "7:00 PM \u2013 9:30 PM",
          timezone: "Asia/Manila (PHT)",
          format: "Live on Zoom",
          earlyBirdDeadline: "July 24, 2026 (11:59 PM PHT)"
        })
      }
    ]
  })
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get REST Reset pricing",
  description: "Returns Early Bird and regular pricing plus the Early Bird deadline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          currency: "PHP",
          earlyBirdPrice: 999,
          regularPrice: 1499,
          earlyBirdDeadline: "July 24, 2026 (11:59 PM PHT)",
          paymentMethods: ["Xendit", "GCash", "Maya", "Debit Cards"]
        })
      }
    ]
  })
});

// src/lib/mcp/tools/get-checkout-url.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_checkout_url_default = defineTool3({
  name: "get_checkout_url",
  title: "Get REST Reset checkout URL",
  description: "Returns the Xendit checkout URL for enrolling in REST Reset.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: () => ({
    content: [{ type: "text", text: "https://checkout.xendit.co/od/RESTJuly2026" }]
  })
});

// src/lib/mcp/tools/get-rest-framework.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_rest_framework_default = defineTool4({
  name: "get_rest_framework",
  title: "Get REST framework",
  description: "Returns the four pillars of the REST framework (Regulate, Explore, Separate, Talk).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          R: { name: "Regulate", summary: "Calm the nervous system so healing can begin." },
          E: { name: "Explore", summary: "Gently understand what shaped your patterns." },
          S: { name: "Separate", summary: "Untangle your identity from old wounds." },
          T: { name: "Talk", summary: "Speak to yourself and others with compassion." }
        })
      }
    ]
  })
});

// src/lib/mcp/index.ts
var projectRef = "ippkefhwndptxnlwtugc";
var mcp_default = defineMcp({
  name: "rest-reset-mcp",
  title: "REST Reset",
  version: "0.1.0",
  instructions: "Tools for the REST Reset July 2026 event by Learning While Healing. Requires sign-in. Use these tools to answer questions about the event schedule, pricing, checkout link, and the REST framework.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_event_info_default, get_pricing_default, get_checkout_url_default, get_rest_framework_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
